# EDA 

 ## Table of Contents

 ## 1. [Load Dataset](#load)
 
 ## 2. [EDA with data](#eda)
 
 ###  &nbsp;  2.1 [Data modifying by manually](#manually)
 ###  &nbsp;  2.3 [Data engineering with crawling](#crawling)
 ###  &nbsp;  2.2 [Data engineering with Mechanics](#mechanics)

## 1. Load Dataset <a name="load"></a>

In [1]:
import pandas as pd
import numpy as np
import sys, os
from tqdm import tqdm
import pickle

In [2]:
df = pd.read_csv("./dataset/bgg_data_set.csv",encoding="utf-8")

### Data Description

0. **ID**  : Boardgame Id in BoardGame Geek
1. **Name** : Name of the boardgame
2. **Year Published** : Year of the boardgame published
3. **Min Players** : Minimum players for playing the game
4. **Max Players** : Maximum Players for playing the game
5. **Play Time** : It takes time to play the game generally
6. **Min Age** : Minimum ages to play the game
7. **Users Rated** : How many user votes to
8. **Rating Average** : average score from the users that estimate the game from 0 to 10 (Target)
9. **BGG Rank** : Rank by Rating Average by Descending Order
10. **Complexity Average** : average score from the user that estimate the complexity of the game from 0 to 10 (Candidate Target)
11. **Owned Users** : How many users own the games
12. **Mechanics** : what kinds of mechanics are in the game.
13. **Domains** : The type of the game

### Data Rename for Simplifying

0. ID  : **Id**
1. Name 
2. Year Published : **Year**
3. Min Players : **Minplayers**
4. Max Players : **Maxplayers**
5. Play Time : **Time**
6. Min Age : **Age**
7. Users Rated : **Users_rated**
8. Rating Average : **Rating**
9. BGG Rank : **Rank**
10. Complexity Average : **Complexity**
11. Owned Users : **Own**
12. Mechanics : 
13. Domains :

In [3]:
df.rename(columns = {'ID':"Id",
                     "Year Published":"Year",
                     "Min Players":"Minplayers",
                     "Max Players":"Maxplayers",
                     "Play Time": "Time",
                     "Min Age" : "Age",
                     "Users Rated":"Users_rated",
                     "Rating Average":"Rating",
                     "BGG Rank":"Rank",
                     "Complexity Average":"Complexity",
                     "Owned Users":"Own"}, inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20343 entries, 0 to 20342
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           20327 non-null  float64
 1   Name         20343 non-null  object
 2   Year         20342 non-null  float64
 3   Minplayers   20343 non-null  int64
 4   Maxplayers   20343 non-null  int64
 5   Time         20343 non-null  int64
 6   Age          20343 non-null  int64
 7   Users_rated  20343 non-null  int64
 8   Rating       20343 non-null  float64
 9   Rank         20343 non-null  int64
 10  Complexity   20343 non-null  float64
 11  Own          20320 non-null  float64
 12  Mechanics    18745 non-null  object
 13  Domains      10184 non-null  object
dtypes: float64(5), int64(6), object(3)
memory usage: 2.2+ MB

## 2. EDA with data <a name="eda"></a>

### 2.1 Data modifying by manually <a name="manually"></a>

#### 2.1.1 setting missing id value by finding manually

In [5]:
df.loc[df.Id.isna()]

,Id,Name,Year,Minplayers,Maxplayers,Time,Age,Users_rated,Rating,Rank,Complexity,Own,Mechanics,Domains
10776,NaN,Ace of Aces: Jet Eagles,1990.0,2,2,20,10,110,6.26,10778,2.00,NaN,NaN,NaN
10835,NaN,Die Erben von Hoax,1999.0,3,8,45,12,137,6.05,10837,2.00,NaN,NaN,NaN
11152,NaN,Rommel in North Africa: The War in the Desert ...,1986.0,2,2,0,12,53,6.76,11154,4.00,NaN,NaN,NaN
11669,NaN,Migration: A Story of Generations,2012.0,2,4,30,12,49,7.20,11671,2.00,NaN,NaN,NaN
12649,NaN,Die Insel der steinernen Wachter,2009.0,2,4,120,12,49,6.73,12651,3.00,NaN,NaN,NaN
12764,NaN,Dragon Ball Z TCG (2014 edition),2014.0,2,2,20,8,33,7.03,12766,2.50,NaN,NaN,NaN
13282,NaN,Dwarfest,2014.0,2,6,45,12,82,6.13,13284,1.75,NaN,NaN,NaN
13984,NaN,Hus,NaN,2,2,40,0,38,6.28,13986,2.00,NaN,NaN,NaN
14053,NaN,Contrario 2,2006.0,2,12,0,14,37,6.30,14055,1.00,NaN,NaN,NaN
14663,NaN,Warage: Extended Edition,2017.0,2,6,90,10,49,7.64,14665,3.00,NaN,NaN,NaN
16292,NaN,Rainbow,2010.0,2,6,20,8,35,5.65,16294,2.00,NaN,NaN,NaN
17009,NaN,"Sexy, el juego del arte del flirteo",2014.0,3,4,120,18,39,5.83,17011,2.00,NaN,NaN,NaN
18672,NaN,Dracarys Dice Don't Get Burned!,2018.0,2,5,15,10,86,5.33,18674,1.00,NaN,NaN,NaN
19332,NaN,Battleship: Tactical Capital Ship Combat 1925-...,1986.0,2,2,90,8,131,5.07,19334,2.00,NaN,NaN,NaN
19474,NaN,The Umbrella Academy Game,2020.0,1,6,40,12,41,3.16,19476,1.00,NaN,NaN,NaN
20040,NaN,Hidden Conflict,2005.0,2,6,30,10,128,4.35,20042,2.00,NaN,NaN,NaN

In [6]:
nan_id_idx = df.loc[df.Id.isna()].index

In [7]:
df.loc[df.Id.isna()].Name

10776                              Ace of Aces: Jet Eagles
10835                                   Die Erben von Hoax
11152    Rommel in North Africa: The War in the Desert ...
11669                    Migration: A Story of Generations
12649                     Die Insel der steinernen Wachter
12764                     Dragon Ball Z TCG (2014 edition)
13282                                             Dwarfest
13984                                                  Hus
14053                                          Contrario 2
14663                             Warage: Extended Edition
16292                                              Rainbow
17009                  Sexy, el juego del arte del flirteo
18672                      Dracarys Dice Don't Get Burned!
19332    Battleship: Tactical Capital Ship Combat 1925-...
19474                            The Umbrella Academy Game
20040                                      Hidden Conflict
Name: Name, dtype: object

In [8]:
df.query("Name.str.contains('Hus')")

,Id,Name,Year,Minplayers,Maxplayers,Time,Age,Users_rated,Rating,Rank,Complexity,Own,Mechanics,Domains
10834,20834.0,Husarengolf,1997.0,2,4,15,8,38,7.28,10836,0.00,63.0,NaN,NaN
11785,111026.0,"Op?ration Husky, Sicile 1943",2011.0,2,2,180,0,33,7.06,11787,2.22,149.0,Area Movement,Wargames
13984,NaN,Hus,NaN,2,2,40,0,38,6.28,13986,2.00,NaN,NaN,NaN
16937,6573.0,Husch Husch kleine Hexe,1994.0,2,6,15,3,79,5.51,16939,1.00,166.0,"Dice Rolling, Memory, Roll / Spin and Move",Children's Games
17118,12316.0,Sky My Husband,2004.0,2,8,15,12,33,5.36,17120,1.00,82.0,NaN,NaN
17576,223034.0,Dungeon Hustle,2017.0,2,4,45,14,67,5.49,17578,1.50,229.0,"Pattern Building, Variable Player Powers",NaN
18316,14423.0,Husker Du?,1970.0,1,4,15,4,97,5.42,18318,1.11,199.0,Memory,Children's Games

##### set some data by hand

In [9]:
nan_id_idx_id = [1991, 413, 11113, 143663, 54501, 168077, 170337, 25999, 27227, 198886, 73574, 148211, 269573, 8173, 316555, 15804]

In [10]:
df.loc[nan_id_idx, ["Id", "Name"]]

       Id                                               Name
10776 NaN                            Ace of Aces: Jet Eagles
10835 NaN                                 Die Erben von Hoax
11152 NaN  Rommel in North Africa: The War in the Desert ...
11669 NaN                  Migration: A Story of Generations
12649 NaN                   Die Insel der steinernen Wachter
12764 NaN                   Dragon Ball Z TCG (2014 edition)
13282 NaN                                           Dwarfest
13984 NaN                                                Hus
14053 NaN                                        Contrario 2
14663 NaN                           Warage: Extended Edition
16292 NaN                                            Rainbow
17009 NaN                Sexy, el juego del arte del flirteo
18672 NaN                    Dracarys Dice Don't Get Burned!
19332 NaN  Battleship: Tactical Capital Ship Combat 1925-...
19474 NaN                          The Umbrella Academy Game
20040 NaN                                    Hidden Conflict

In [11]:
for idx, id in zip(nan_id_idx, nan_id_idx_id):
    df.loc[idx, "Id"] = id 
df.Id = df.Id.astype(int)

In [12]:
df.loc[df.Id.isna()].Name

Series([], Name: Name, dtype: object)

#### 2.1.2 finding and setting year of the game's published year denoted as NAN

In [13]:
df.loc[df.Year.isna()].index

Int64Index([13984], dtype='int64')

Cause only one entry has nan at "Year Published" and At BoardGameGeek(a.k.a BGG), there is no feature ("published Year") for the data, so we'll drop it.

In [14]:
df.drop(index = df.loc[df.Year.isna()].index, inplace = True)

In [15]:
df.loc[df.Year.isna()].index

Int64Index([], dtype='int64')

In [16]:
df.Year = df.Year.astype(int)

2.1.2 Result

In [17]:
df.head(5)

,Id,Name,Year,Minplayers,Maxplayers,Time,Age,Users_rated,Rating,Rank,Complexity,Own,Mechanics,Domains
0,174430,Gloomhaven,2017,1,4,120,14,42055,8.79,1,3.86,68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,161936,Pandemic Legacy: Season 1,2015,2,4,60,13,41643,8.61,2,2.84,65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,224517,Brass: Birmingham,2018,2,4,120,14,19217,8.66,3,3.91,28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,167791,Terraforming Mars,2016,1,5,120,12,64864,8.43,4,3.24,87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,233078,Twilight Imperium: Fourth Edition,2017,3,6,480,14,13468,8.70,5,4.22,16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"

#### 2.1.3. Data Correction

In [18]:
# original id is wrong
df.loc[5691, "Id"] = 283152   # Monikers: Serious Nonsense
df.loc[9329, "Id"] = 255249   # Monikers: More Monikers
df.loc[9391, "Id"] = 242879   # Ladrillazo
df.loc[14426, "Id"] = 2607    # Totopoli
df.drop(index= [14143, 15637], inplace = True)

In [19]:
print(df.loc[5691, ["Id", "Name"]])
print(df.loc[9329, ["Id", "Name"]])
print(df.loc[9391, ["Id", "Name"]])
print(df.loc[14426,["Id", "Name"]])

Id        283152
Name    Monikers
Name: 5691, dtype: object
Id                       255249
Name    Monikers: More Monikers
Name: 9329, dtype: object
Id          242879
Name    Ladrillazo
Name: 9391, dtype: object
Id          2607
Name    Totopoli
Name: 14426, dtype: object

### 2.2 Data engineering with crawling <a name="crawling"></a>

 missing value handling with xml by BGG api

In [20]:
import xml.etree.ElementTree as ET
from urllib.request import urlopen

In [21]:
df.reset_index(drop=True, inplace=True)

In [22]:
df_ = df.copy()

In [23]:
def poll_weighted_sum(poll_dict, suggest_only_one):
    
    numvotes = "numvotes"
    
    mapping = {"Best" : 3,
               "Recommended" : 2,
               "Not Recommended": 1}
        
    result = {}
    
    for main_subject, sub in poll_dict.items():
        if type(sub) == list:
            values = 0.
            counts = 0
            if main_subject == "language_dependence":
                for elem in sub:
                    count = int(elem[numvotes])
                    value = int(elem['level']) * count
                    counts += count
                    values += value
            elif main_subject == "suggested_playerage":
                for elem in sub:
                    count = int(elem[numvotes])
                    if (elem["value"] != "21 and up"):
                        value = int(elem["value"]) * count
                    else:
                        value = 21 * count
                        
                    counts += count
                    values += value
                    
            if counts > 0:
                values = values / counts
            else:
                values = np.nan                        
            result[main_subject] = values
            
        elif type(sub) == dict:
            rate_list  = []
            rate_value = []
            for subject, sub_list in sub.items():
                name = subject.split("__")[1]
                counts = 0
                values = 0
                for v in sub_list:
                    count = int(v[numvotes])
                    value = mapping[v["value"]] * count
                    
                    counts += count
                    values += value
                
                if counts > 0:
                    values /= counts
                else:
                    values = np.nan
                rate_list.append(subject+"_"+name)
                rate_value.append(values)
                
                if suggest_only_one == False:
                   result[main_subject+"_"+name] = values 
                            
            if suggest_only_one:
                
                if(max(rate_value) > 0):
               
                    max_idx = max(range(len(rate_value)), key=lambda i: rate_value[i])
                    result[main_subject] = max_idx
                
                else:
                    
                    result[main_subject] = np.nan
    return result  

def get_data_from_bgg(id, args = {"suggest_only_one" : True,
                    }):
    base_url = "https://boardgamegeek.com/xmlapi/boardgame/"

    add_url = "?stats=1"

    watch_list = [["yearpublished","Year"],
                ["minplayers","Minplayers"],
                ["maxplayers","Maxplayers"],
                ["playingtime","Time"],
                ["minplaytime","Mintime"],
                ["maxplaytime","Maxtime"],
                ["age","Age"]]


    watch_list_all = [["boardgamecategory","Category"],
                      ["boardgamedesigner","Designer"],
                      ["boardgameartist","Artist"],
                      ["boardgamesubdomain","Domains"],
                      ["boardgamemechanic", "Mechanics"]]

    results = {"Id":id}

    final_url = base_url+str(id)+add_url
    
    
    response = urlopen(final_url).read()
    xtree = ET.fromstring(response)[0]
    polls_dict = {}
        
    for watch, watch_name in watch_list:
        results[watch_name] = xtree.find(watch).text

    for xt in xtree.findall("name"):
        if "primary" in xt.attrib.keys():
            results["Name"] = xt.text
        
        
    for watch, watch_name in watch_list_all:
        results[watch_name] = []
        for elem in xtree.findall(watch):
            results[watch_name].append(elem.text)

    for polls in xtree.iter("poll"):
        poll_dict = {}
        for poll in polls:      
            sub_list = []
            if len(poll.attrib) > 0: 
                pass
            for vote in poll:
                sub_list.append(vote.attrib)
            if len(polls) == 1:
                poll_dict = sub_list
            else:
                poll_dict['__'.join(list(*poll.attrib.items()))] = sub_list
        polls_dict[polls.attrib['name']] = poll_dict
    
    
    polls_result = poll_weighted_sum(polls_dict, args["suggest_only_one"])
    
    results.update(polls_result)
    
    return results

# get_data_from_bgg(174430) # example

In [24]:
file_name = "crawled2.csv"
if os.path.isfile("dataset\\"+file_name):
    need2crawl = False
else: 
    need2crawl = True

In [25]:
# for test
# print(len(l))
# df_.loc[14143]
# get_data_from_bgg(df_.loc[14143].Id)

In [26]:
if need2crawl:
    l = []

In [27]:
if need2crawl:
    for idx in tqdm(df_.index[len(l):]):
        l.append(get_data_from_bgg(df_.iloc[idx].Id))

In [28]:
if need2crawl:
    crawled = pd.DataFrame(l).rename(columns = {"suggested_numplayers":"Sug_players",
                                                "language_dependence":"Language_dependence",
                                                "suggested_playerage":"Sug_age"})

    crawled["Id"] = df_.Id

    crawled = crawled[["Id",
                    "Name",
                    "Year",
                    "Minplayers",
                    "Maxplayers",
                    "Sug_players",
                    "Time",
                    "Mintime",
                    "Maxtime",
                    "Age",
                    "Sug_age",
                    "Mechanics",
                    "Domains",
                    "Category",
                    "Designer",
                    "Artist",
                    "Language_dependence"]]
    # for savingg
    crawled.to_csv("dataset\\crawled2.csv")
else:
    crawled = pd.read_csv("dataset\\crawled2.csv").drop(columns=["Unnamed: 0"])

In [29]:
crawled

,Id,Name,Year,Minplayers,Maxplayers,Sug_players,Time,Mintime,Maxtime,Age,Sug_age,Mechanics,Domains,Category,Designer,Artist,Language_dependence
0,174430,Gloomhaven,2017,1,4,2.0,120,60,120,14,12.781879,"['Action Queue', 'Action Retrieval', 'Campaign...","['Strategy Games', 'Thematic Games']","['Adventure', 'Exploration', 'Fantasy', 'Fight...",['Isaac Childres'],"['Alexandr Elichev', 'Josh T. McDowell', 'Alva...",4.187500
1,161936,Pandemic Legacy: Season 1,2015,2,4,3.0,60,60,60,13,11.329480,"['Action Points', 'Cooperative Game', 'Hand Ma...","['Strategy Games', 'Thematic Games']","['Environmental', 'Medical']","['Rob Daviau', 'Matt Leacock']",['Chris Quilliams'],4.095745
2,224517,Brass: Birmingham,2018,2,4,2.0,120,60,120,14,13.245455,"['Hand Management', 'Income', 'Loans', 'Market...",['Strategy Games'],"['Economic', 'Industry / Manufacturing', 'Post...","['Gavan Brown', 'Matt Tolman', 'Martin Wallace']","['Lina Cossette', 'David Forest', 'Damien Mamm...",1.054054
3,167791,Terraforming Mars,2016,1,5,2.0,120,120,120,12,11.967552,"['Closed Drafting', 'Contracts', 'Enclosure', ...",['Strategy Games'],"['Economic', 'Environmental', 'Industry / Manu...",['Jacob Fryxelius'],['Isaac Fryxelius'],3.395833
4,233078,Twilight Imperium: Fourth Edition,2017,3,6,5.0,480,240,480,14,14.307692,"['Action Drafting', 'Area Majority / Influence...","['Strategy Games', 'Thematic Games']","['Civilization', 'Economic', 'Exploration', 'N...","['Dane Beltrami', 'Corey Konieczka', 'Christia...",['Scott Schomburg'],4.130435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20335,16398,War,0,2,2,1.0,30,30,30,4,4.357143,[],"[""Children's Games""]","['Card Game', ""Children's Game""]",['(Uncredited)'],['Jim Davis'],1.000000
20336,7316,Bingo,1530,2,99,16.0,60,60,60,5,4.777778,"['Betting and Bluffing', 'Bingo', 'Pattern Rec...",['Party Games'],"[""Children's Game"", 'Movies / TV / Radio theme...",['Edwin S. Lowe'],"['Laura Bernard', 'Theodor Seuss Geisel', 'Kev...",1.055556
20337,5048,Candy Land,1949,2,4,3.0,30,30,30,3,3.325581,['Roll / Spin and Move'],"[""Children's Games""]","[""Children's Game"", 'Racing']",['Eleanor Abbott'],['(Uncredited)'],1.052632
20338,5432,Chutes and Ladders,-200,2,6,3.0,30,30,30,3,3.355556,"['Grid Movement', 'Race', 'Roll / Spin and Mov...","[""Children's Games""]","['Animals', ""Children's Game"", 'Movies / TV / ...",['(Uncredited)'],"['Wilhelm Busch', 'Lauren Child', 'Lucy Cousin...",1.000000
20339,11901,Tic-Tac-Toe,-1300,2,2,1.0,1,1,1,4,4.217391,"['Paper-and-Pencil', 'Pattern Building', 'Squa...","['Abstract Games', ""Children's Games""]","['Abstract Strategy', ""Children's Game""]",['(Uncredited)'],[],1.032258

##### Data Merging

There are many wrong value in given dataset, so we collect data from BGG api.

From given dataset (df_), we only preserve columns which are 
- Name
- Users_rated
- Rating
- Rank
- complexity
- Own

From crawled dataset (crawled), we drop columns which are
- Name

In [33]:
org = df_.copy()

org.drop(columns = ["Year", "Minplayers", "Maxplayers", "Time", "Age", "Mechanics", "Domains"], inplace=True)
print(org.shape)
org.head()

(20340, 7)

,Id,Name,Users_rated,Rating,Rank,Complexity,Own
0,174430,Gloomhaven,42055,8.79,1,3.86,68323.0
1,161936,Pandemic Legacy: Season 1,41643,8.61,2,2.84,65294.0
2,224517,Brass: Birmingham,19217,8.66,3,3.91,28785.0
3,167791,Terraforming Mars,64864,8.43,4,3.24,87099.0
4,233078,Twilight Imperium: Fourth Edition,13468,8.70,5,4.22,16831.0

In [34]:
mod = crawled.copy()
mod.drop(columns = ["Name"], inplace=True)
print(mod.shape)
mod.head()

(20340, 16)

,Id,Year,Minplayers,Maxplayers,Sug_players,Time,Mintime,Maxtime,Age,Sug_age,Mechanics,Domains,Category,Designer,Artist,Language_dependence
0,174430,2017,1,4,2.0,120,60,120,14,12.781879,"['Action Queue', 'Action Retrieval', 'Campaign...","['Strategy Games', 'Thematic Games']","['Adventure', 'Exploration', 'Fantasy', 'Fight...",['Isaac Childres'],"['Alexandr Elichev', 'Josh T. McDowell', 'Alva...",4.187500
1,161936,2015,2,4,3.0,60,60,60,13,11.329480,"['Action Points', 'Cooperative Game', 'Hand Ma...","['Strategy Games', 'Thematic Games']","['Environmental', 'Medical']","['Rob Daviau', 'Matt Leacock']",['Chris Quilliams'],4.095745
2,224517,2018,2,4,2.0,120,60,120,14,13.245455,"['Hand Management', 'Income', 'Loans', 'Market...",['Strategy Games'],"['Economic', 'Industry / Manufacturing', 'Post...","['Gavan Brown', 'Matt Tolman', 'Martin Wallace']","['Lina Cossette', 'David Forest', 'Damien Mamm...",1.054054
3,167791,2016,1,5,2.0,120,120,120,12,11.967552,"['Closed Drafting', 'Contracts', 'Enclosure', ...",['Strategy Games'],"['Economic', 'Environmental', 'Industry / Manu...",['Jacob Fryxelius'],['Isaac Fryxelius'],3.395833
4,233078,2017,3,6,5.0,480,240,480,14,14.307692,"['Action Drafting', 'Area Majority / Influence...","['Strategy Games', 'Thematic Games']","['Civilization', 'Economic', 'Exploration', 'N...","['Dane Beltrami', 'Corey Konieczka', 'Christia...",['Scott Schomburg'],4.130435

In [35]:
df_new = org.merge(mod, on="Id")
print(df_new.shape)

(20346, 22)

In [36]:
df_new.drop_duplicates(subset="Id", inplace=True)
print(df_new.shape)

(20337, 22)

In [37]:
df = df_new.copy()

  
### Additional features Description

  ##### basically use weighted sum (value * votes)

  ##### (1) suggested_numplayers
  
     Best            -> 1
     Recommended     -> 0
     Not Recommended -> -1

  ##### (2) langugage_dependence

     No necessary in-game text                                         -> 1 
     Some necessary text - easily memorized or small crib sheet        -> 2
     Moderate in-game text - needs crib sheet or paste ups             -> 3
     Extensive use of text - massive conversion needed to be playable  -> 4
     Unplayable in another language                                    -> 5

  ##### (3) suggested_playerage

      2 : ~ 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      8 : 7 ~ 8
      10 : 9 ~ 10
      12 : 11 ~ 12
      14 : 13 ~ 14
      16 : 15 ~ 16
      18 : 17 ~ 18
      21 : 19 ~

### 2.3 Data engineering with new Dataset <a name="mechanics"></a>

##### 2.3.1 split and get new features from Mechanics

In [38]:
def str2list(x, type=None):
    
    
    if type == "mechanics":
        x = x.apply(lambda x: x.replace("\'", "\"").replace("Prisoner\"s Dilemma", "Prisoners Dilemma").replace("\"", "'"))
    
    elif type == "artist":
        pass

    elif type == "domains" or type == "category":
        x = x.apply(lambda x: x.replace("\'", "\"").replace("Children\"s Games", "Childrens Games").replace("\"", "'"))
    
    elif type == "designer":
        pass
    
    elif type == None:
        pass
    
    return x.apply(lambda x: x[1:-1].replace("', '", "'|'").replace("'","").split("|")
                                        ).apply(lambda x: x if len(x) > 2 else (x if x[0] != '' else []))

In [39]:
not_eq = df[str2list(df.Mechanics, "mechanics") != str2list(df.Mechanics, None)].index

In [40]:
df_ = df.copy()
df_.reset_index(drop=True, inplace=True)
if need2crawl == False:
        
    df_.Mechanics = str2list(df_.Mechanics, "mechanics")
    df_.Domains = str2list(df_.Domains, "domains")
    df_.Designer = str2list(df_.Designer)
    df_.Category = str2list(df_.Category, "category")
    df_.Artist = str2list(df_.Artist)

In [41]:
print(f"the number of domain is {len(df_.Domains.apply(pd.Series).stack().reset_index(drop=True).unique())}")

C:\Users\pokem\AppData\Local\Temp\ipykernel_16728\1442128251.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(f"the number of domain is {len(df_.Domains.apply(pd.Series).stack().reset_index(drop=True).unique())}")

the number of domain is 8

In [42]:
print(f"the number of Designer is {len(df_.Designer.apply(pd.Series).stack().reset_index(drop=True).unique().tolist())}")

C:\Users\pokem\AppData\Local\Temp\ipykernel_16728\2452927176.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(f"the number of Designer is {len(df_.Designer.apply(pd.Series).stack().reset_index(drop=True).unique().tolist())}")

the number of Designer is 9336

In [43]:
print(f"the number of Category is {len(df_.Category.apply(pd.Series).stack().reset_index(drop=True).unique().tolist())}")

C:\Users\pokem\AppData\Local\Temp\ipykernel_16728\1034434647.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(f"the number of Category is {len(df_.Category.apply(pd.Series).stack().reset_index(drop=True).unique().tolist())}")

the number of Category is 83

In [44]:
print(f"the number of Artist is {len(df_.Artist.apply(pd.Series).stack().reset_index(drop=True).unique().tolist())}")

C:\Users\pokem\AppData\Local\Temp\ipykernel_16728\2126513075.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(f"the number of Artist is {len(df_.Artist.apply(pd.Series).stack().reset_index(drop=True).unique().tolist())}")

the number of Artist is 10699

In [45]:
# if there is no Mechanics
print(f"The number of nan at Mechanics : {df_.Mechanics.apply(lambda x : len(x) == 0).sum()}")

The number of nan at Mechanics : 1466

##### how many mechanics are there

In [46]:
mechanics = []    # total

for idx in df_.index:
    mechanic = df_["Mechanics"].loc[idx]
    mechanics += mechanic

In [47]:
mechanics_set = list(set(mechanics))
print("The number of Unique Mechanics :",len(mechanics_set))

The number of Unique Mechanics : 187

##### List of the machanics

In [48]:
mechanics_set

['Income',
 'Point to Point Movement',
 'Track Movement',
 'Action Points',
 'Critical Hits and Failures',
 'Auction: Fixed Placement',
 'Paper-and-Pencil',
 'Ratio / Combat Results Table',
 'Lose a Turn',
 'Action/Event',
 'Programmed Movement',
 'Auction: Sealed Bid',
 'Force Commitment',
 'Memory',
 'Mancala',
 'Turn Order: Stat-Based',
 'Prisoners Dilemma',
 'Physical Removal',
 'Hexagon Grid',
 'Investment',
 'Tile Placement',
 'Negotiation',
 'Time Track',
 'Cube Tower',
 'Elapsed Real Time Ending',
 'Neighbor Scope',
 'Scenario / Mission / Campaign Game',
 'Deck, Bag, and Pool Building',
 'Victory Points as a Resource',
 'Highest-Lowest Scoring',
 'Race',
 'Re-rolling and Locking',
 'Command Cards',
 'King of the Hill',
 'Move Through Deck',
 'Relative Movement',
 'Worker Placement, Different Worker Types',
 'Increase Value of Unchosen Resources',
 'Map Reduction',
 'Ownership',
 'Modular Board',
 'Turn Order: Auction',
 'Pick-up and Deliver',
 'I Cut, You Choose',
 'Auction: Dutch Priority',
 'Constrained Bidding',
 'Once-Per-Game Abilities',
 'Hand Management',
 'Predictive Bid',
 'Single Loser Game',
 'Events',
 'Turn Order: Progressive',
 'Simultaneous Action Selection',
 'Finale Ending',
 'Impulse Movement',
 'Grid Coverage',
 'Passed Action Token',
 'Closed Economy Auction',
 'Commodity Speculation',
 'Melding and Splaying',
 'Static Capture',
 'Induction',
 'Communication Limits',
 'Area-Impulse',
 'Storytelling',
 'Rock-Paper-Scissors',
 'Hidden Movement',
 'Chaining',
 'Crayon Rail System',
 'Card Play Conflict Resolution',
 'Cooperative Game',
 'Role Playing',
 'Enclosure',
 'Matching',
 'Connections',
 'Roles with Asymmetric Information',
 'Bias',
 'Variable Phase Order',
 'Player Judge',
 'Worker Placement',
 'Turn Order: Pass Order',
 'Real-Time',
 'Map Deformation',
 'Resource to Move',
 'Take That',
 'Slide/Push',
 'Multi-Use Cards',
 'Turn Order: Role Order',
 'Alliances',
 'Interrupts',
 'Different Dice Movement',
 'Stock Holding',
 'Narrative Choice / Paragraph',
 'Flicking',
 'Action Drafting',
 'Follow',
 'Area Movement',
 'Measurement Movement',
 'Hot Potato',
 'Deck Construction',
 'Network and Route Building',
 'Bribery',
 'Trick-taking',
 'Legacy Game',
 'Open Drafting',
 'Speed Matching',
 'Action Queue',
 'Bingo',
 'Pattern Recognition',
 'Push Your Luck',
 'End Game Bonuses',
 'Simulation',
 'Movement Points',
 'Area Majority / Influence',
 'Secret Unit Deployment',
 'Questions and Answers',
 'Map Addition',
 'Kill Steal',
 'Roll / Spin and Move',
 'Closed Drafting',
 'Semi-Cooperative Game',
 'Stacking and Balancing',
 'Order Counters',
 'Auction: Dexterity',
 'Chit-Pull System',
 'Stat Check Resolution',
 'Variable Set-up',
 'Voting',
 'Line Drawing',
 'Pieces as Map',
 'Worker Placement with Dice Workers',
 'Dice Rolling',
 'Ladder Climbing',
 'Solo / Solitaire Game',
 'Hidden Victory Points',
 'Square Grid',
 'Movement Template',
 'Automatic Resource Growth',
 'Auction: English',
 'Delayed Purchase',
 'Contracts',
 'Auction: Once Around',
 'Betting and Bluffing',
 'Hidden Roles',
 'Selection Order Bid',
 'Auction/Bidding',
 'Die Icon Resolution',
 'Moving Multiple Units',
 'Tug of War',
 'Multiple Maps',
 'Rondel',
 'Campaign / Battle Card Driven',
 'Random Production',
 'Set Collection',
 'Auction: Dutch',
 'Score-and-Reset Game',
 'Line of Sight',
 'Action Retrieval',
 'Layering',
 'Singing',
 'Player Elimination',
 'Market',
 'Ordering',
 'Acting',
 'Trading',
 'Auction: Turn Order Until Pass',
 'Variable Player Powers',
 'Team-Based Game',
 'Zone of Control',
 'Tech Trees / Tech Tracks',
 'Catch the Leader',
 'Deduction',
 'Grid Movement',
 'Loans',
 'Multiple-Lot Auction',
 'Turn Order: Random',
 'Turn Order: Claim Action',
 'Pattern Building',
 'Targeted Clues',
 'Pattern Movement',
 'Three Dimensional Movement',
 'Action Timer',
 'Sudden Death Ending',
 'Auction Compensation',
 'Advantage Token',
 'Minimap Resolution',
 'Traitor Game']

##### How many the kinds of mechanics, domains, category, designer and artist in each game

In [54]:
get_number = lambda x : x.apply(lambda y: len(y))

In [55]:
get_number(df_.Mechanics)

0        21
1         8
2         8
3        16
4        17
         ..
20332     0
20333     3
20334     1
20335     4
20336     3
Name: Mechanics, Length: 20337, dtype: int64

New feature created that how many that features in the game

In [56]:
df_["Nmechanics"] = get_number(df_.Mechanics)
df_["Ndomains"] =get_number(df_.Domains)
df_["Nartist"] = get_number(df_.Artist)
df_["Ndesign"] = get_number(df_.Designer)
df_["Ncategory"] = get_number(df_.Category)

In [57]:
df_.Year = df_.Year.astype(int)
df_.Minplayers = df_.Minplayers.astype(int)
df_.Maxplayers = df_.Maxplayers.astype(int)
df_.Time = df_.Time.astype(int)
df_.Mintime = df_.Mintime.astype(int)
df_.Maxtime = df_.Maxtime.astype(int)
df_.Age = df_.Age.astype(int)

In [58]:
# csv
df_.to_csv("dataset\\new_bgg_data_after_eda.csv", index=False)

In [59]:
# to pickle
with open("dataset//new_bgg_data_after_eda.pickle", 'wb') as f:
    pickle.dump(df_, f)